### ISSUE TITLE
Build fail for Windows on r-universe

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#106]
https://github.com/r-universe/ropensci/runs/5199808357?check_suite_focus=true#step:8:675

**Comment by peterdesmet** [comment]
Not a lot of context for the error, but:

```
  - "  ]\r"
  + "  ]"
  - "}\r"
  + "}"
```

I think it relates to this test:

https://github.com/frictionlessdata/frictionless-r/blob/40c9374654c88ba4ee5afefa11764b6238883ba9/tests/testthat/test-write_package.R#L56

It looks like on Windows, `jsonlite:toJSON()` does not add `\r` in line breaks, while the original `inst/extdata/datapackage.json` does have those line breaks.

**Comment by peterdesmet** [comment]
@damianooldoni @lienreyserhove could either of you try on your Windows laptop:

1. Clone the repository: https://github.com/frictionlessdata/frictionless-r
2. Open in R Studio
3. Run `devtools::test()` ?

**Comment by damianooldoni** [comment]
![image](https://user-images.githubusercontent.com/33662631/154261976-de9375af-496f-441b-9779-ac17b4d439ac.png)

Everything works fine. Before `devtools::test()` I run `devtools::install()`, of course.

**Comment by peterdesmet** [comment]
Fixed in e7f7231
