### ISSUE TITLE
Ideas for write functions

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#11]
Ideas for write functions:

## create_package() from scratch

See #43

## create_schema() for a df

See #12

## ✅  get_schema() from a resource

```R
get_schema("resource_name", pkg)
```

- [x] If we order arguments like this, then also do `read_resource("gps", pkg)`

## add_resource() to a package

See #44

## ✅ remove_resource()

```R
remove_resource("name", pkg)
```

- [x] Ask a "are you sure?" question before the removal? **no, blocks flow and user has to save into new variable anyway**

## write_package() to a directory

See #42

**Comment by peterdesmet** [comment]
Use case:

```R
# Read input datapackage
nphk <- read_package("https://zenodo.com/nphk/datapackage.json")
dep_df <- read_resource(nphk, "deployments")
obs_df <- read_resource(nphk, "observations")
mm_df <- read_resource(nphk, "multimedia")

# Some fancy transformations to make Darwin Core
dwc_occ_df <- dep_df %>%
  left_join(obs_df, ...) %>%
  mutate() %>%
  mutate()
dwc_mm_df <- dep_mm %>%
  ...

# Add Darwin Core df as resources to data package (mostly their schema)
nphk <- add_resource(nphk, dwc_occ_df, "dwc_occurrence")
nphk <- add_resource(nphk, dwc_occ_df, "dwc_multimedia")
# Add properties not set by add_resource() e.g.g foreign keys:
nphk$resources[[5]]$schema$foreignKeys <- ...

# Write to file
write_package(nphk, "nphk")
# Writes nphk to nphk/datapackage.json
# Copy/pastes deployments.csv, observations.csv, multimedia.csv from Zenodo to nphk/
# Writes dwc_occ_df and dwc_mm_df as dwc_occurrence.csv and dwc_multimedia.csv to nphk/
```

**Comment by damianooldoni** [comment]
I like this set of functions and they seem very coherent with the goal of this R package.

Some notes:
1. `create_package()`: I see this like one of the handy functions of `usethis` package. It would be nice to allow users to pass some information to start a new data package which is a little more than a dummy. Something like a vector of resource names?
2. `create_package()` is much better as name than `init_package` from a R user point of view, I think. `init_*` is very Pythonic and less used in the R community
3. _"Do we also need remove_resource()?"_ yes, I think it could be a useful function to have as it can happen that you made a mistake and you want to cancel a df. Of course a "are you sure?" question has to be asked before the removal? Similar to many other `usethis` functions
4. It seems you want `pacakge` as first argument of all functions where `pacakge` is needed. I understand the idea, but in `add_resource(package, df, "name")` it sounds to me a little strange as the natural way to read this function is "I add `df` x to `package` y and I assign it the `name` z". I have this feeling also when I see the example in the use case: `add_resource(nphk, dwc_occ_df, "dwc_occurrence")`. I would use `add_resource(dwc_occ_df, nphk, "dwc_occurrence")`. It depends of course if we are going to have many other functions with arg `package` in this package.

**Comment by peterdesmet** [comment]
Thanks for the feedback, much appreciated!

For the position of the `package` parameter, I think we should use what works will when piping, so I think you're right that `add_resource()` might have the `df` first:

```R
read_resource(package, "observations") %>%
  mutate() %>%
  mutate() %>%
  add_resource(package, "changed_observations")
```

**Comment by peterdesmet** [comment]
This issue is now broken down in several issues. Closing this.
