### ISSUE TITLE
Pack package to conda-forge

### ISSUE THREAD

**Issue by rgaiacs** [frictionlessdata/frictionless-r#110]
I would like to have the package available from [conda-forge](https://conda-forge.org/) to enable me to include it in the conda environment file of my project.

For your information, I created a PR to conda-forge covering my feature request: https://github.com/conda-forge/staged-recipes/pull/19720.

**Comment by peterdesmet** [comment]
Cool! Is there any action required from my end?

And out of interest: what does this enable you (and I assume other conda-forge) users to do?

**Comment by rgaiacs** [comment]
The package is available at conda-forge. See https://github.com/conda-forge/r-frictionless-feedstock.

> Is there any action required from my end?

No. If you like, you can subscribe to receive notifications to https://github.com/conda-forge/r-frictionless-feedstock.

> what does this enable you

Installation from conda-forge is a lot faster than CRAN. The main reason is that conda-forge compile the code and user only need to download the binary. Also, frictionless can be listed in the conda environment description file. For example, I'm writing a few notes about frictionless data using [Quarto](https://quarto.org/). The notes are available at https://raniere-phd.gitlab.io/frictionless-data-handbook/ and the code at https://gitlab.com/raniere-phd/frictionless-data-handbook. The code is compiled using Docker configured from a conda environment (see https://gitlab.com/raniere-phd/frictionless-data-handbook/-/blob/main/env.yaml).

**Comment by peterdesmet** [comment]
Great, thanks! Very cool to read https://raniere-phd.gitlab.io/frictionless-data-handbook/create-data-package-with-r.html.
