### ISSUE TITLE
suppress messages from read_package

### ISSUE THREAD

**Issue by PietrH** [frictionlessdata/frictionless-r#121]
## Description

`read_package()` is used in testthat tests within frictionless, where they are locally supressed [for example:](https://github.com/frictionlessdata/frictionless-r/blob/main/tests/testthat/test-read_package.R#L5)

```
p_local <- suppressMessages(read_package(p_path))
```

I also want to use `frictionless::read_package()` in some tests for a different package: etn. I'd like to propose adding an argument to the function to suppress messaging like:

> Please make sure you have the right to access data from this Data Package
    for your intended use.\nFollow applicable norms or requirements to credit
    the dataset and its authors.

I imagine this argument could be something like: 

```
silent = TRUE
silently = TRUE
supress_messages = TRUE
verbose = FALSE
show_messages = FALSE
```

I'll have a go at making this change myself, and adding an appropriate test + changing the tests to use the new argument instead of local versions of the `read_package()` function. 

## Proposed changes

- [ ] add argument to read_package()
- [ ] add coverage for new argument in test-read_package()
- [ ] change existing tests to make use of new argument

## Scope

I'm not proposing to suppress the assertions/checks made by `asserthat`, just the `message()` call ([link to line](https://github.com/frictionlessdata/frictionless-r/blob/421c22f8be948006c5fb89a822124fbb803dff12/R/read_package.R#L64))

**Comment by peterdesmet** [comment]
From rOpenSci it was recommended:

> I tend to use verbose for adding extra information (default FALSE) and quiet for suppressing standard messages (default FALSE).

I agree with this and would use `quiet` as parameter name.

**Comment by peterdesmet** [comment]
See guidance in this new blog post: https://ropensci.org/blog/2024/02/06/verbosity-control-packages/

**Comment by peterdesmet** [comment]
`read_package()` no longer returns a message, see https://github.com/frictionlessdata/frictionless-r/pull/155/commits/b75ab20bb6ae74e7c5231032adebb8d74555e7a4 reverting #21 behaviour.
