### ISSUE TITLE
Mention `deposits` package in Vignette

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#133]
A very promising [`deposits` package](https://github.com/ropenscilabs/deposits) is currently being developed. It aids users with submitting (and retrieving) research products to (and from) Zenodo and Figshare. It relies on the `frictionless` R package to document items with metadata.

We currently conclude our vignette with:

https://github.com/frictionlessdata/frictionless-r/blob/888bc97e62269704bfeaf52f3ebc3a084d3009d3/vignettes/frictionless.Rmd#L258-L262

That seems like a good place to mention the `deposits` package. My main question is timing, as `deposits` is currently indicated as Work In Progress. @mpadge any advice?

**Comment by mpadge** [comment]
Thanks for connecting here @peterdesmet - I'll contact you via rOpenSci slack for discussion before proceding here.
