### ISSUE TITLE
Documentation build error

### ISSUE THREAD

**Issue by khusmann** [frictionlessdata/frictionless-r#156]
FYI, when running `devtools::document()`, the build fails with the following warning/error when `rlist` is not installed:

```
ℹ Updating frictionless documentation
ℹ Loading frictionless
Warning message:
[utils.R:36] @description refers to unavailable topic rlist::list.clean
Caused by error in `find.package()`:
! there is no package called ‘rlist’ 
```

Not sure if there's any way around this... is it possible to make this reference valid without installing rlist?

Alternatively, you might consider just using `purrr::keep`, `purrr::discard`, and `purr:compact`, I think they do basically the same thing and you're already requiring purrr.

In any case, it's very low priority because it's an internal function & only affect developers -- just wanted to give you the heads up.

**Comment by peterdesmet** [comment]
Thanks for reporting. The culprit might be:

https://github.com/frictionlessdata/frictionless-r/blob/0881f1c4bbd0c5f679a4f74665e9acd7df0554af/R/utils.R#L39

in a helper function which merely mentions rlist in the function description. I did not realize `devtools::document()` requires referenced functions to be installed. I think we can remove the reference (or write it differently), no `Rd` is created anyway.

**Comment by peterdesmet** [comment]
@khusmann you suggest to use `purrr::compact()` which indeed does the default functionality of `clean_list()`, but only at one level deep. Is there a way to do this recursively? If not, then I'll just keep my helper function.

**Comment by khusmann** [comment]
I believe early versions of purrr included recursive options for some of its functions like this, but they have since been removed because they are ["hard to get right"](https://github.com/tidyverse/purrr/issues/720). Looks like that discussion resulted in `modify_tree()`

So a recursive `compact()` on list `x` would be: `modify_tree(x, post = compact)`. But if that's too verbose, keeping the helper function is nbd.
