### ISSUE TITLE
Consider using `rlang::%||%` over `replace_null()`

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#175]
See https://masalmon.eu/2023/06/06/basic-patterns/ There is an rlang function `%||%` that has same functionality as `replace_null()`.

Advantages:

- Existing functionality

Disadvantages:

- New dependency... although, seems it is already used in

https://github.com/frictionlessdata/frictionless-r/blob/f7f3fe3b2077843113538428c51a1f2d9a736b9a/R/read_resource.R#L379-L381

- More clunky to call with namespace `rlang::%||%`, would have to revert to `%||%`

**Comment by khusmann** [comment]
I definitely prefer `%||%` to `replace_null()`. Much more concise and readable, in my opinion.

Regarding scoping, it's common practice for packages in the tidyverse universe to import the entire rlang library and use it unscoped: https://github.com/tidyverse/ggplot2/issues/3195

Given that the goals of this package mention alignment with tidyverse ("It is designed to be lightweight, follows tidyverse principles and supports piping."), I think it makes sense to use all of rlang's niceties when available.

And it's not a new dependency -- readr, dplyr and purrr all import rlang... so I think we might as well use it.
