### ISSUE TITLE
Add `replace = FALSE` to `add_resource()`

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#227]
Sometimes you want to edit a resource in place. `add_resource()` currently forbids that.

- Alternative 1: have a `replace = TRUE` attribute in `add_resource()` (default FALSE)
- Alternative 2: have a `replace_resource()` function

I prefer alternative 1. We will be to use this attribute/function in https://github.com/inbo/camtrapdp/issues/74

**Comment by PietrH** [comment]
I prefer `replace = TRUE`
