### ISSUE TITLE
Check the package supports minimal R version automatically

### ISSUE THREAD

**Issue by damianooldoni** [frictionlessdata/frictionless-r#233]
At the moment frictionless supports R version 3.5 or higher.

I would add `- {os: ubuntu-latest,   r: '3.5'}` in [R-CMD-check.yaml#L20-L25](https://github.com/frictionlessdata/frictionless-r/blob/main/.github/workflows/R-CMD-check.yaml#L20-L25) to test if this version is really supported smoothly.

**Comment by peterdesmet** [comment]
This is implemented in #245 (as version 3.6.0).
