### ISSUE TITLE
replace magrittr pipes with base pipes in examples

### ISSUE THREAD

**Issue by PietrH** [frictionlessdata/frictionless-r#239]
- [ ] list usage of magrittr pipes
- [ ] replace with base pipes
- [ ] test examples

**Comment by PietrH** [comment]
blocked by #238

**Comment by peterdesmet** [comment]
See https://github.com/frictionlessdata/frictionless-r/pull/242#issuecomment-2220368797. Base pipes are only introduced since R4.1.0.
