### ISSUE TITLE
not required column and un-ordered columns in `add_resource()`

### ISSUE THREAD

**Issue by Rafnuss** [frictionlessdata/frictionless-r#254]
I'm not expecting an error message when adding a resource which has a column missing which is not required according to the schema.

Here [https://raw.githubusercontent.com/Rafnuss/GeoLocator-DP/main/measurements-table-schema.json] does not require the `valid` column, which is missing in my data. 

```r
library(frictionless)
create_package() |>
  add_resource(
    "measurements",
    data.frame(
      "tag_id" = "18LY",
      "sensor" = "pressure", 
      "datetime" = "2020-05-01", 
      "value" = 12
    ),
    schema = jsonlite::read_json("https://raw.githubusercontent.com/Rafnuss/GeoLocator-DP/main/measurements-table-schema.json"))
#> Error in `check_schema()`:
#> ! Field names in `schema` must match column names in `data`.
#> ℹ Field names: "tag_id", "sensor", "datetime", "value", and "valid".
#> ℹ Column names: "tag_id", "sensor", "datetime", and "value".
```

Also I am not sure why providing in the same order than in the schema is necessary. Is it no possible to re-order the data according to schema? 

```r
library(frictionless)
create_package() |>
  add_resource(
    "measurements",
    data.frame(
      "tag_id" = "18LY",
      "sensor" = "pressure", 
      "datetime" = "2020-05-01", 
      "valid" = F,
      "value" = 12
    ),
    schema = jsonlite::read_json("https://raw.githubusercontent.com/Rafnuss/GeoLocator-DP/main/measurements-table-schema.json"))
#> Error in `check_schema()`:
#> ! Field names in `schema` must match column names in `data`.
#> ℹ Field names: "tag_id", "sensor", "datetime", "value", and "valid".
#> ℹ Column names: "tag_id", "sensor", "datetime", "valid", and "value".
```

**Comment by Rafnuss** [comment]
If you think this makes sense, I can improve the suggestion, but here is just a first idea. Not sure if I'm missing something...

**Comment by peterdesmet** [comment]
Hi @Rafnuss, you (and many others, including me) want optional and reordered fields.

This feature that is not supported in Data Package 1.0, which is the version that frictionless currently implements. So right now, you (annoyingly) need to add all columns in your data, even if those are empty. Or you will need to do some preprocessing on your schema before adding it to your resource.

The feature has indeed been added as [fieldsMatch](https://datapackage.org/standard/table-schema/#fieldsMatch) in Data Package 2.0. Frictionless currently doesn't support 2.0 yet, but we aim to do so (including [fieldMatch](https://github.com/frictionlessdata/frictionless-r/issues/216)). Fully supporting v2 is a [daunting task](https://github.com/frictionlessdata/frictionless-r/labels/datapackage%3Av2) though, so it won't be soon.
