### ISSUE TITLE
`rbind.data.frame()` returns factors in older versions of R

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#267]
We're almost there in regards to [supporting R3.6.0](https://github.com/frictionlessdata/frictionless-r/pull/245). [One test](https://github.com/frictionlessdata/frictionless-r/actions/runs/10936419521/job/30360019805?pr=245) is failing, caused by reading the inline data with `rbind.data.frame()`:

https://github.com/frictionlessdata/frictionless-r/blob/feaad88d0463d3bab919396ffc5a8639d0c2b1f5/R/read_resource.R#L56-L59

In R3.6.0 this returns factors, while newer versions of R return characters. We expect characters:

https://github.com/frictionlessdata/frictionless-r/blob/feaad88d0463d3bab919396ffc5a8639d0c2b1f5/tests/testthat/test-read_resource.R#L271-L276

How to not use factors? Are there better alternatives than `rbind.data.frame()`?

Example (on recent version of R):

```R
library(frictionless)
x <- example_package()
inline_data <- x$resources[[3]]$data
df <- do.call(rbind.data.frame, inline_data)

df$media_id
#> [1] "aed5fa71-3ed4-4284-a6ba-3550d1a4de8d"
#> [2] "da81a501-8236-4cbd-aa95-4bc4b10a05df"
#> [3] "0ba57608-3cf1-49d6-a5a2-fe680851024d"
class(df$media_id)
#> [1] "character"
```

**Comment by damianooldoni** [comment]
As mentioned in chat, @peterdesmet, can you try this?

```r
library(frictionless)
x <- example_package()
inline_data <- x$resources[[3]]$data
df <- do.call(rbind.data.frame, c(inline_data, stringAsFactors = FALSE))
# Check structure
str(df)
```

**Comment by peterdesmet** [comment]
Fixed with https://github.com/frictionlessdata/frictionless-r/commit/b28af6c6cd45766716f9b8cf6215a95adbd7618a.
