### ISSUE TITLE
Can we remove rlist dependency?

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#45]
We currently use `rlist` for one step:

https://github.com/frictionlessdata/frictionless-r/blob/750eef30fa1e29d5bd5611e99ae1ef748c90de95/R/create_schema.R#L117-L122

It might be worth investigating if this functionality cannot be replace with base R and purrr:: code.

**Comment by damianooldoni** [comment]
Inspired by [stackoverflow](https://stackoverflow.com/questions/26539441/remove-null-elements-from-list-of-lists), we can do it in base R (without `purrr`) by defining a basic function:

```r
#' tests whether an object is either NULL or an empty list
is.NullOb <- function(x) {
  is.null(x) | 
    (!is.null(x) & length(x) == 0L)
}
```

and then applying recursively to all list (schema):

```r
#' Recursively step down into list, removing all such objects
rmNullObs <- function(x) {
  x <- Filter(Negate(is.NullOb), x)
  lapply(x, function(x) if (is.list(x)) rmNullObs(x) else x)
}
```

**Comment by damianooldoni** [comment]
If you prefer to use purrr's `map()` instead of basic R's `lapply()`:

```r
rmNullObs_purrr <- function(x) {
  x <- Filter(Negate(is.NullOb), x)
  purrr::map(x, function(x) if (is.list(x)) rmNullObs(x) else x)
}
rmNullObs_purrr(a)
```

Although I am a fan of tidyverse and I like purrr a lot, I don't see a benefit in using `purrr::map()` in this specific situation.

**Comment by peterdesmet** [comment]
The first suggestion does not remove an empty list. Here's the expectation:

```R
schema <- list(
  fields = list(
    list(
      name = "col_1",
      type = "number",
      constraints = list(
        enum = NULL
      )
    ),
    list(
      name = "col_2",
      type = "string",
      constraints = list(
        enum = c("a", "b", "c")
      )
    )
  )
)

expected_schema <- list(
  fields = list(
    list(
      name = "col_1",
      type = "number"
      # No constraints
    ),
    list(
      name = "col_2",
      type = "string",
      constraints = list(
        enum = c("a", "b", "c")
      )
    )
  )
)
```
