### ISSUE TITLE
Can we remove stringr dependency?

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#46]
Currently used once:

https://github.com/frictionlessdata/frictionless-r/blob/750eef30fa1e29d5bd5611e99ae1ef748c90de95/R/read_resource.R#L246-L248

**Comment by damianooldoni** [comment]
basic R function `gsub()` should be what we need 👍 

```r
> names <- c("Damiano", "Peter", "Dimi")
> gsub(x = names, pattern = "i", replacement = "o")
[1] "Damoano" "Peter"   "Domo"  
```

**Comment by peterdesmet** [comment]
Hmm, but I have defined my replacements beforehand as `key = value`s, i.e. a named vector called `translations`. How do I pass that to the function?

```R
translations <- c(
  "^default$" = "%Y-%m-%d"
  "^any$" = "%AD"
  "^%x$" = "%m/%d/%y
)
format <- "any"

do_something(format, translations)
# format is now the value "%AD"
```
