### ISSUE TITLE
"$ operator is invalid for atomic vectors" error when data package use external dialect property

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-r#49]
In the section [On dereferencing and descriptor validation](https://specs.frictionlessdata.io/guides/implementation/#on-dereferencing-and-descriptor-validation) the frictionless specs say that

> Some properties in the Frictionless Data specifications allow a path (a URL or a POSIX path) that resolves to an object.
> 
> The most prominent example of this is the `schema` property on Tabular Data Resource descriptors.
> 
> Allowing such references has practical use for publishers, for example in allowing schema reuse. However, it does introduce difficulties in the validation of such properties. For example, validating a path pointing to a schema rather than the schema object itself will do little to guarantee the integrity of the schema definition. Therefore implementors `MUST` dereference such "referential" property values before attempting to validate a descriptor. At present, this requirement applies to the following properties in Tabular Data Package and Tabular Data Resource:
> 
> - `schema`
> - `dialect`

`frictionless-r` doesn't dereference the dialect property, resulting in the error _$ operator is invalid for atomic vectors_ in the calls to dialect properties such as `dialect$delimiter` (eg. https://github.com/frictionlessdata/frictionless-r/blob/main/R/read_resource.R#L312). Here is a reprex

``` r
library(frictionless)

dp <- read_package("https://raw.githubusercontent.com/dados-mg/datapackage-reprex/external-dialect/datapackage.json")
#> Please make sure you have the right to access data from this Data Package for your proposed use.
#> Follow applicable norms or requirements to credit the dataset and its authors.

res <- read_resource("estados", dp)
#> Error: $ operator is invalid for atomic vectors
```

We make extensive use of this feature in the data packages of the [Open Data Portal of Minas Gerais](https://github.com/dados-mg) and I would be happy to submit a PR by next week if there is interest.

**Comment by peterdesmet** [comment]
Thanks for reporting this so clearly. External schemas should indeed be supported. I am already creating a PR to support this.

**Comment by peterdesmet** [comment]
@fjuniorr should be fixed by installing the latest version of the package:

```
devtools::install_github("frictionlessdata/frictionless-r")
```
