### ISSUE TITLE
Allow to add resources with a path

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#74]
One might want to create a data package from csv files on disk. In that case it should be possible to use `write_package()` to just write the `datapackage.json` to disk and not read/write all the csv files.

On disk, in directory `my_dir`:

```
gps-2018.csv
gps-2019.csv
```

```R
my_package <- create_package()

# Create resource
gps <- read_csv("my_dir/gps-2018.csv")
add_resource(
  my_package,
  resource_name = "ref",
  df = ref, # Not used to write data, only to create schema
  path = c("my_dir/gps-2018.csv", "my_dir/gps-2019.csv") # Define path
)
# Sets resource "path", does not add inline "data"

# Write package
write_package(package, directory = "my_dir")
# Detects that some of the paths contain "my_dir" and:
# - Does not write the files to disk
# - Shortens the path to just the file names
```

Caveats:
- CSV dialect, delimiters, etc. not known.

**Comment by peterdesmet** [comment]
Note that the current behaviour of `write_package()` is already to not overwrite existing csv files, so files won't be needlessly copied in case on writes to the same directory.

**Comment by peterdesmet** [comment]
Rather than reusing `add_resource()`, we could also create a new function:

```R
add_resource_from_csv(
  my_package,
  resource_name = "ref",
  path = c("my_dir/gps-2018.csv", "my_dir/gps-2019.csv"),
  # schema = if you have customized the schema
)
```

Since the function also reads the csv, it has a better chance of knowing what the dialect etc. is.

**Comment by peterdesmet** [comment]
@damianooldoni thoughts?

**Comment by peterdesmet** [comment]
I'm leaning towards keeping the same function, but renaming the `df` argument to `data`. If it is a data frame, it follows the current behaviour. If it is character, it assumes the data are a path to csv files:

```R
add_resource(
  my_package,
  data = "path_to/data.csv",
  schema = my_schema
)
```

**Comment by damianooldoni** [comment]
You are in a typical development phase: ease the life of users by including some preprocessing steps in the package, typically as hidden steps. The main reason for doing it in the case of `frictionless` is that it fits perfectly with its goal: reading csvs, appending them as recources, reading schemas, ... all these steps should be as smooth as possbile for the users. And what I like at most of your last comment is the fact that you still allow the user to pass a data.frame to `data`.

I also vote for exporting ONE function only: if you want to use an help function `add_resource_from_csv()`, you can do it but it should be an internal function used behind the screen. Actually it's good practice to factorize the code by measn of subfunctions where it is possible and not trivial.
