### ISSUE TITLE
`read_resource` can't read resources with encoding UTF-8 with BOM

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-r#86]
As noted in https://github.com/frictionlessdata/specs/issues/613, the [Data Resource](https://specs.frictionlessdata.io/data-resource/#optional-properties) spec doesn't specify how the [byte order mark (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark) should be handled. It is also worth noting that, probably because UTF-8 with BOM is not an encoding _per se_, it is not [registered with IANA](https://www.iana.org/assignments/character-sets/character-sets.xhtml) and therefore doesn't have a preferred MIME name.

When using `frictionless.py` describe, it will use the identifier `utf-8-sig`. However, `readr` [doesn't expect anything explicit](https://github.com/tidyverse/readr/issues/1187#issuecomment-811847866) for reading csv files with BOM, and we get the following error

``` r
library(frictionless)

dp <- read_package("https://raw.githubusercontent.com/dados-mg/datapackage-reprex/utf-8-bom/datapackage.json")

dp |> read_resource("utf-8-bom")
#> Error: Unknown encoding utf-8-sig
```

It might be a good idea to simply replace `utf-8-sig` and `utf-8-bom` (and the uppercase versions) with `utf-8`.

Ps. Although the use of [BOM is neither required nor recommended](https://en.wikipedia.org/wiki/Byte_order_mark#cite_note-4), we are currently using BOM in the files that we produce because of the large number of excel users among the consumers of our data.

**Comment by peterdesmet** [comment]
Thanks for reporting so clearly! I will implement a more general solution where a warning is raised for unknown encodings (because I notice some IANA listed ones like `latin-greek` are also not recognized) and the file is read with UTF-8:

```R
> dp |> read_resource("utf-8-bom")
#> # A tibble: 1 × 1                                                                          
#>   v    
#>   <chr>
#> 1 €    
#> Warning message:
#> In read_resource(dp, "utf-8-bom") :
#>   Unknown encoding `utf-8-sig`. Reading file(s) with UTF-8 encoding.
```

**Comment by peterdesmet** [comment]
@fjuniorr this functionality is now available in the development version on the `main` branch. Your example now gives this:

``` r
library(frictionless)

dp <- read_package("https://raw.githubusercontent.com/dados-mg/datapackage-reprex/utf-8-bom/datapackage.json")
#> Please make sure you have the right to access data from this Data Package for your intended use.
#> Follow applicable norms or requirements to credit the dataset and its authors.

dp |> read_resource("utf-8-bom")
#> Warning in read_resource(dp, "utf-8-bom"): Unknown encoding `utf-8-sig`. Reading
#> file(s) with UTF-8 encoding.
#> # A tibble: 1 × 1
#>   v    
#>   <chr>
#> 1 €
```

<sup>Created on 2022-01-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think warning for unknown encodings is important. For users to know that parsing might be off. And for authors of data packages that they are using an encoding that is not recognized.

**Comment by fjuniorr** [comment]
> I think warning for unknown encodings is important. For users to know that parsing might be off. And for authors of data packages that they are using an encoding that is not recognized.

Totally agree! Thanks for the quick fix!

**Comment by ThrawnCA** [comment]
Attempting to validate a UTF-8 BOM file still has issues, eg the BOM is incorporated into the first column name, which then doesn't match the schema.
