### ISSUE TITLE
Use `format=csv` for extension `csv.gz`

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#90]
For a path ending in `csv.gz`, `add_resource()` will write `format = gz`. It would be more correct if this was set to `format = csv, compression = gz`. See https://specs.frictionlessdata.io/patterns/#specification-3

**Comment by peterdesmet** [comment]
`compression = gz` throws an error in `frictionless-py validate` if the csv has no data. It does not when there is an _implied compression_ (no `compression` property). Still, the format for `csv.gz` should be `csv`, not `gz`.

**Comment by peterdesmet** [comment]
Ideally, the function should be able to set the format as follows for the following file names:

```
"file.name.csv.gz"  # csv
"file.name.txt.gz"  # txt
"file.name.csv.zip" # csv
"file.name.txt.zip" # txt
"file.name.csv"     # csv
"file.name.txt"     # txt
"file.name.gz"      # gz
"file.name"         # ""
"file_name"         # ""
```

**Comment by peterdesmet** [comment]
@niconoe any ideas on how to parse the above?

**Comment by damianooldoni** [comment]
Something like this?

```
library(stringr)

splitted_string <- str_split(
  c("file.name.csv.gz",
    "file.name.txt.gz",
    "file.name.csv.zip",
    "file.name.txt.zip",
    "file.name.csv",
    "file.name.txt",
    "file.name.gz",
    "file.name",
    "file_name"), 
  pattern = "\\."
)
purrr::map_chr(splitted_string, function(x) {
  if (length(x) >= 3) {
    x[3]
  } else {
    ""
  }
})
#> [1] "csv" "txt" "csv" "txt" "csv" "txt" "gz"  ""    ""
```
Created on 2022-01-21 by the reprex package (v2.0.1)

**Comment by damianooldoni** [comment]
@peterdesmet: hehe, indeed. I started quite blindly from your example in https://github.com/frictionlessdata/frictionless-r/issues/90#issuecomment-1018571787

**Comment by peterdesmet** [comment]
This is an implementation that works: https://github.com/frictionlessdata/frictionless-r/commit/d2c1b4a500a1cd4df188441dcd712828d27809d2

But looking at the specs again, I'm considering dropping it completely. The [definition](https://specs.frictionlessdata.io/data-resource/#optional-properties) says:

> `format`: ‘csv’, ‘xls’, ‘json’ etc. Would be expected to be the standard file
extension for this type of resource.

The type of resource `add_resource()` is always a delimited text file. Not an `xls` or `json` file, since those can't be read by `read_csv()` in the function. The next question is then, what is the _standard_ file extension for delimited text file. I would argue that is `csv`, not `txt` or `tab`, irrespective of delimiter. One could argue for `tsv` for tab-delimited files, but that flavour is already indicated in `mediatype`. I'll thus implemented it as:

- delimiter `,` => csv
- delimiter `\t` => tsv
- delimiter anything else => csv

**Comment by damianooldoni** [comment]
I find it a very reasonable choice. Yes, `csv` is very typically used even for delimiters others than `,`.
