### ISSUE TITLE
Create function `resources(package)`

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#97]
Suggested by @beatrizmilz in https://github.com/ropensci/software-review/issues/495#issuecomment-1025860861

> There is some examples that are shown using lists. What do the authors think about using functions instead, to be more standardized? Example: create a function `resources(package)` to use it instead of `package$resource_names`.

**Comment by peterdesmet** [comment]
@damianooldoni especially for getting `package$resource_names` I like this suggestion, as is it something a user almost always has to do when exploring a package. I'm just wondering what name would be best:

```R
resources(example_package)
#> [1] "deployments"  "observations" "media"

resource_names(example_package)
#> [1] "deployments"  "observations" "media"
```

**Comment by damianooldoni** [comment]
Indeed, interesting suggestion by @beatrizmilz!

`list_resources()` and `resource_names` are too long for what they do and I tend to forget them fast.

I think easier the better in this case, so I vote for the first one.

I have also a even more simple option in mind: why not using the singular version of it, i.e. `resource()`? The reason is that all functions are singular: `add_resource`, `read_resource`, `remove_resource`.

**Comment by peterdesmet** [comment]
Thanks, I prefer `resources()` too. The singular functions always act on a single item, `resources()` returns a vector of (often multiple) resources, so I would keep it plural.

Another question is where to [group this function](https://frictionlessdata.github.io/frictionless-r/reference/index.html) (i.e. function family). I'm tempted to say this is a `read_` function, not a miscellaneous one:

<img width="702" alt="Screenshot 2022-02-01 at 10 38 06" src="https://user-images.githubusercontent.com/600993/151944979-876e7d82-c690-4447-b924-14af7bdc3553.png">

I think I'll write the function title as "List Data Resources" not "List Data Resource names"

**Comment by damianooldoni** [comment]
Yes, Peter you are right: `resources` is the best name then.

And yes, it's definitely a read function, I agree 100%
